KerasJson: example-keras-model-files/KERAS_3layer_95pruned_retrained.json
KerasH5:   example-keras-model-files/KERAS_3layer_95pruned_retrained_weights.h5
OutputDir: my-hls-dir-test

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
DefaultPrecision: ap_fixed<18,8> 
